services:
  playwright-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright_docker
    working_dir: /app
    volumes:
      - $PWD:/app
    command: npm run test