services:
  playwright-test:
    image: mcr.microsoft.com/playwright:v1.53.1-noble
    build: .
    container_name: playwright_docker
    working_dir: /app
    volumes:
      - $PWD:/app
    command: npm run test
